-- insert into product (id, name, description, price) values (1, 'Cupcake', 'Nutritious and imported', 6.33);
-- insert into product (id, name, description, price) values (2, 'Dickery', 'Do not attempt this at home!', 420.31415);
-- insert into product (id, name, description, price) values (3, 'Macaron', 'Flavourful filling per customer`s choice', 20);
